"""empty message

Revision ID: 265ea1d587a3
Revises: None
Create Date: 2014-10-22 13:43:08.178132

"""

# revision identifiers, used by Alembic.
revision = '265ea1d587a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
  ### commands auto generated by Alembic - please adjust! ###
  op.create_table('task',
  sa.Column('id', sa.String(), nullable=False),
  sa.Column('active', sa.Boolean(), nullable=True),
  sa.Column('code', sa.Text(), nullable=True),
  sa.Column('interval', sa.Integer(), nullable=True),
  sa.PrimaryKeyConstraint('id')
  )
  ### end Alembic commands ###


def downgrade():
  ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('task')
  ### end Alembic commands ###
