"""Initial migration

Revision ID: 69423a89666
Revises: None
Create Date: 2014-10-21 18:11:40.366483

"""

# revision identifiers, used by Alembic.
revision = '69423a89666'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
  ### commands auto generated by Alembic - please adjust! ###
  op.create_table('board',
  sa.Column('id', sa.String(), nullable=False),
  sa.Column('board_data', sa.String(), nullable=True),
  sa.PrimaryKeyConstraint('id')
  )
  ### end Alembic commands ###


def downgrade():
  ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('board')
  ### end Alembic commands ###
